### ISSUE TITLE
[Android] Support new permissions for Android 13 (API 33)

### ISSUE THREAD

**Issue by simonpham** [Baseflow/flutter-permission-handler#859]
## 🚀 Feature Requests

Since Android 13, there are many new permissions introduced. We will need to update to support it all.

There are 22 new permissions. Hence I list the most important ones (likely)
![image](https://user-images.githubusercontent.com/8846657/175206056-eddc5261-d9ac-4b04-9881-624ed12711f1.png)

- [x] [POST_NOTIFICATIONS](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS) - https://github.com/Baseflow/flutter-permission-handler/pull/845
- [x] [READ_MEDIA_AUDIO] #941 #934 #933
- [x] [READ_MEDIA_IMAGES] #941 #934 #933
- [x] [READ_MEDIA_VIDEO] #941 #934 #933
- [x] [NEARBY_WIFI_DEVICES](https://developer.android.com/reference/android/Manifest.permission#NEARBY_WIFI_DEVICES)
- [x] [SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM) - #941 #934 #933

Ref:
- https://developer.android.com/reference/android/Manifest.permission
- https://developer.android.com/about/versions/13/features

### Platforms affected
- [x] :robot: Android

**Comment by aytunch** [comment]
I have a question. If we update the package to version 10.0.0, and upgrade sdk version to 33, does this mean our users with android phones with version 12 and less wont be able to use the app? Or is it backwards compatible with older OS too?

**Comment by ArmandoJimenezOS** [comment]
SCHEDULE_EXACT_ALARM is automatically granted and declared in the manifest, but we can check if it's enabled since users can disable it in the "special app access" screen. I think the one we need to request now is USE_EXACT_ALARM?

**Comment by armandojimenez** [comment]
Any plans for this? Android 13 is already out

**Comment by alexmercerind** [comment]
What is costing you to merge the pull request?

**Comment by YannickMaljaars** [comment]
READ_MEDIA_IMAGES, READ_MEDIA_VIDEOS and READ_MEDIA_AUDIO should also be supported as of my recent PR's for these have been merged!

For reference:
[PR 941](https://github.com/Baseflow/flutter-permission-handler/pull/941)
[PR 934](https://github.com/Baseflow/flutter-permission-handler/pull/934)
[PR 933](https://github.com/Baseflow/flutter-permission-handler/pull/933)

If you experience issues with these, please make a new issue explaining your problems!

**Comment by simonpham** [comment]
Since all requested permissions are supported, I will close this issue.
If anyone have any request, please re-open or just create a new issue.

Thank you for your contribution! @YannickMaljaars @alex-sandri
